config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'welcome#home'
get 'about_us', to: 'welcome#about_us'
get 'speak_to_us', to: 'welcome#speak_to_us'

get 'ec_journalists', to: 'services#ec_journalists'
get 'linkedin', to: 'services#linkedin'
get 'instagram', to: 'services#instagram'
get 'youtube', to: 'services#youtube'

namespace :admin do
  resources :clients
end

get 'client_profile', to: 'client#client_profile'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :username, presence: true

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < AdminController

  def admin_profile

  end

  def edit

  end

  def new
    @client = Client.new
  end

  def create
    render plain: params[:client].inspect
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/admin_controller.rb
class AdminController < ApplicationController

  def admin_profile

  end

  def client_base

  end

  def edit_client

  end

  def new_client
    @client = Client.new
  end

  def create
    render plain: params[:client].inspect
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def ec_journalists

  end

  def instagram

  end

  def linkedin

  end
  def youtube

  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def about_us

  end

  def speak_to_us

  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin_profile.html.erb
<center>
<p> </p>
<h1>Admin profile</h1>
<p1> This where you might get alerts about stuff, links to all various tools/resources we have and the client base doc of course ✌🏻 </p1>
<hr>
<p2> Here's the <%= link_to "client base", client_base_path %></p2>
<p></p>
<p2> And here's the link to go back to the <%= link_to "homepage", root_path %></p2>
</center>

app/views/admin/client_base.html.erb
<center>
<p> </p>
<h1>Client Base</h1>
<p1> These are all our maaany clients! </p>
<hr>
<p2> And back to your <%= link_to "profile", admin_profile_path %></p2>
</center>

app/views/admin/clients/client_profile.html.erb
<center>
<p> </p>
<h1>Client profile</h1>
<p1> here you'll find all our great resources links, info on your package, an email address to reach out to to request a cancellation, FAQ's, links to other tools as we make them like hashtag curators etc. </p1>
<hr>
<p2> And here's the link to go back to the <%= link_to "homepage", root_path %></p2>
</center>

app/views/admin/edit.html.erb
<center>
<p> </p>
<h1>Edit client</h1>
<hr>
<p2> And back to your <%= link_to "profile", admin_profile_path %></p2>
</center>

app/views/admin/edit_client.html.erb
<center>
<p> </p>
<h1>Edit client</h1>
<hr>
<p2> And back to your <%= link_to "profile", admin_profile_path %></p2>
</center>

app/views/admin/new.html.erb
<center>
<p> </p>
<h1>New client</h1>
<hr>
<%= form_for @client do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br/><%= f.label :server %>
    <%= f.text_field :server %>
    <br/><%= f.label :contactname %>
    <%= f.text_field :contactname %>
    <br/><%= f.label :contactemail %>
    <%= f.text_field :contactemail %>
    <br/><%= f.label :package %>
    <%= f.text_field :package %>
    <br/><%= f.label :source %>
    <%= f.text_field :source %>
    <br/><%= f.label :paidsam %>
    <%= f.text_field :paidsam %>
    <br/><%= f.label :socialurl %>
    <%= f.text_field :socialurl %>
    <br/><%= f.label :password %>
    <%= f.text_field :password %>
    <br/><%= f.label :price %>
    <%= f.text_field :price %>
    <br/><%= f.label :fbinstarepost %>
    <%= f.text_field :fbinstarepost %>
    <br/><%= f.label :closeio %>
    <%= f.text_field :closeio %>
    <br/><%= f.label :proxy %>
    <%= f.text_field :proxy %>
    <br/><%= f.label :datesold %>
    <%= f.text_field :datesold %>
    <br/><%= f.label :datestarted %>
    <%= f.text_field :datestarted %>
    <br/><%= f.label :startingfollowing %>
    <%= f.text_field :startingfollowing %>

  </p>
  <p>
    <%= f.submit "Add the client" %>
  </p>
<% end %>
<p2> And back to your <%= link_to "profile", admin_profile_path %></p2>
</center>

app/views/admin/new_client.html.erb
<center>
<p> </p>
<h1>New client</h1>
<hr>
<%= form_for @client, url: client_base_path do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br/><%= f.label :server %>
    <%= f.text_field :server %>
    <br/><%= f.label :contactname %>
    <%= f.text_field :contactname %>
    <br/><%= f.label :contactemail %>
    <%= f.text_field :contactemail %>
    <br/><%= f.label :package %>
    <%= f.text_field :package %>
    <br/><%= f.label :source %>
    <%= f.text_field :source %>
    <br/><%= f.label :paidsam %>
    <%= f.text_field :paidsam %>
    <br/><%= f.label :socialurl %>
    <%= f.text_field :socialurl %>
    <br/><%= f.label :password %>
    <%= f.text_field :password %>
    <br/><%= f.label :price %>
    <%= f.text_field :price %>
    <br/><%= f.label :fbinstarepost %>
    <%= f.text_field :fbinstarepost %>
    <br/><%= f.label :closeio %>
    <%= f.text_field :closeio %>
    <br/><%= f.label :proxy %>
    <%= f.text_field :proxy %>
    <br/><%= f.label :datesold %>
    <%= f.text_field :datesold %>
    <br/><%= f.label :datestarted %>
    <%= f.text_field :datestarted %>
    <br/><%= f.label :startingfollowing %>
    <%= f.text_field :startingfollowing %>

  </p>
  <p>
    <%= f.submit "Add the client" %>
  </p>
<% end %>
<p2> And back to your <%= link_to "profile", admin_profile_path %></p2>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  </head>

  <body>

    <% unless action_name == "home" %>
   <%= render 'shared/logo' %>
   <% end %>

    <%= render 'shared/nav' %>

      <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/services/ec_journalists.html.erb
<div class=page-header-text>
  <div class="row">
      <h1 class="display-4 col container">The EC Journalists</h1>
  </div>
</div>
<div class="nb-and-ec-logo">
<h1 class="display-3"><%= image_tag("EC_Journalist.png") %></h1>
</div>

<div class="social-channel-text row">
  <div class="container">
    <p1>Eco Companion is on a mission to save the natural world and the Eco Companion Journalists
      are a community of content creators focused on helping to inspire more people to fall
      in love with the natural world!
      <br>
      <br><%= link_to image_tag("nbandeclogos.png"), "https://www.instagram.com/ec_journalists/" %>
      <br>
      <br>This is right up the Nature Boys street! So we’re proud to have partnered up to support that growth!
      <br>
      <br>Whether you’re a content creator early on in your journey or already
      an award winner global power house - find out more about the group and apply for membership.
      <br>
      <br>Just get in touch by emailing kieran@wearethenatureboys.com with who you are,
      your social pages and why it is you're interested in being an EC Journalist.
       <br>
       <br> or click the link below...
    </p1>
  </div>
</div>

<div class="chat-cta">
  <h2><%=mail_to "kieran@wearethenatureboys.com", "Email us", :subject => "NB ECJ Enquiry", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>

app/views/services/instagram.html.erb
<div class=page-header-text>
  <div class="row">
      <h1 class="display-4 col container">Instagram</h1>
  </div>
  <div class="row">
      <h1 class="display-5 col">Why Instagram</h1>
  </div>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1> Instagram has now reached over 1 billion users
         <br>
         <br>
         The average Instagram post receives over 43 times more engagement
         than any other social channel
         <br>
         <br>
         It is the most important social network to master of the 21st century
    </p1>
  </div>
</div>

<div class="page-break-text-five row">
    <h1 class="display-5 container">What is automation</h1>
</div>

<div class="instagram-explainer">
   <div class="container">
      <div class="homepage-text">
        <h1 class="display-4"><%= image_tag("whatisautomation.png") %></h1>
    </div>
  </div>
</div>

<div class="page-break-text-four row">
    <h1 class="display-5 container">Why is that good</h1>
</div>

<div class="instagram-explainer">
   <div class="container">
      <div class="homepage-text">
        <h1 class="display-4"><%= image_tag("whythatgood.png") %></h1>
    </div>
  </div>
</div>

<div class="page-break-text-two row">
    <h1 class="display-5 container">The Nature Boys difference</h1>
</div>

<div class="social-channel-text">
  <div class="container">
      <p1> We believe that Instagram is a story-telling platform and so in able to tell that story well,
           you have to either invest heavily in to others to go deep in to your business, or do it yourself.
           <br>
           <br>So we leave the story telling you and focus on the growth with
           our 'Growth Plugin Package'
           <br>
           <br>This combines three factors:
      </p1>
      <div class="nb-difference">
        <h1 class="display-4"><%= image_tag("nbdifference.png") %><h1>
    </div>
  </div>
</div>

<div class="page-break-text-six row">
    <h1 class="display-5 container">Engagement upgrades</h1>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1>We then combine our base Growth Plugin Package with other
     tools to maximise engagement and growth.
    </p1>
  </div>
</div>

<div class="pods-and-comments row container">
  <div class="container">
      <div class="pods col-sm-12 col-xs-12 col-md-4 col-lg-4 col-xl-6">
        <div class="container">
          <h2> Engagement Pods </h2>
          <hr>
          <p> We'll have 400 different unique real people autmatically come and
            like your most recent post up to 3 times per day!
            <br>
            <br>This then triggers the Instagram algorithm to have your post seen
            by 10X the number of people and so more eyes on you and your content!
          </p>
      </div>
    </div>
      <div class="comments col-sm-12 col-xs-12 col-md-4 col-lg-4 col-xl-6">
          <div class="container">
            <h2> Manual commenting </h2>
            <hr>
            <p>A member of the Nature Boys team will deliver custom, personalised and
              human comments to your followers and target accounts.
              <br>
              <br>This is the most effective way to drive engagement to your account
              beyond anything else as each comment is naturally reciprocated.
            </p>
        </div>
      </div>
    </div>
</div>

<div class="page-break-text-three row">
    <h1 class="display-5 container">How to go ahead</h1>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1>On a rolling contract (cancel anytime), for our Growth Plugin Package, we charge £149 per month.
      <br>
      <br>Within the first month, you can get all your money back with no questions asked.
      <br>
      <br>For pricing information on engagement pods and manual commenting packages click <%= link_to "here", "https://drive.google.com/file/d/1vo4dSsdovSsHLX9qN6W-Y4ImzoxXICz-/view?usp=sharing" %>.
      <br>
      <br>When you're ready to go ahead, or for more info, email kieran@wearethenatureboys.com
      with the Instagram handle you're looking for help with and the services you're interested in.
       <br>
       <br> or click the link below...
    </p1>
  </div>
</div>
<div class="chat-cta">
  <h2><%=mail_to "kieran@wearethenatureboys.com", "Email us", :subject => "NB Insta Enquiry", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>

app/views/services/linkedin.html.erb
<div class=page-header-text>
  <div class="row">
      <h1 class="display-4 col container">Linkedin</h1>
  </div>
  <div class="row">
      <h1 class="display-5 col">Why Linkedin</h1>
  </div>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1> Linkedin is the biggest sales opportunity for any b2b brand in todays world.
         <br>
         <br>Through intelligent systemisation of the sales flow we're able to drive an amount of leads to any business that changes the issue from "I just can't find leads", to "Our sales team's not big enough!".
    </p1>
  </div>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1> Not only deliver regular leads each week but build a massive social following on one of the biggest and fastest growing networks of today!
    <br>
    <br> The Nature Boys founder Max has delivered great results building multiple startups up with Linkedin as a core channel.
    <br>
    <br> His Linkedin network reaches over 20,000 people offering an entire new content marketing opportunity in itself!
    </p1>
  </div>
</div>

</div>
<div class="page-break-text-five row">
    <h1 class="display-5 container">How can we help</h1>
</div>

<div class="linkedin-paths container row">
  <div class="linkedin-consultancy container col-6">
      <h3> One-to-one consultancy with Max </h3>
      <hr>
      <p1> I’ll show you how to set up a perfect search to get the exact people you’re after and then systemise that outreach.
           <br>
           <br>The final product is so effective that how to manage such a high number of leads sincerely becomes the new problem to solve!
           <br>
           <br>In return for a single upfront fee of £250 we’ll deliver:
           <br>
           <br>
           <ul><li>An initial video call to walk through the entire process and all the steps needed to get started.</li>
               <li>One week on from that, a 2nd call to look at how far you’ve got and if any particular stumbling blocks.</li>
               <li>Then a final call another 2 weeks on to look at how things have progressed and make sure it’s optimised as
                   best it can be and you’re happy with how to run it going forward.</li>
               <li>Plus happy to reply to email questions over that period too with any roadblocks you come up with.</li>
           </ul>
       </p1>
  </div>
  <div class="linkedin-full container col-6">
      <h3> Full blown sales lead management </h3>
      <hr>
      <p1> If you’re interested in us taking on the work for you and handling part or all of your sales flow then no problem.
        <br>
        <br> We’ve worked with individual freelancers, all the way up to major international brands.
        <br>
        <br> Get in touch to set up a call and we can discuss how to best fit what you’re after!
       </p1>
  </div>
</div>
<div class="social-channel-text">
  <div class="container">
    <p1> Email max@wearethenatureboys.com to find out more.
    </p1>
  </div>
</div>
<div class="chat-cta">
  <h2><%=mail_to "max@wearethenatureboys.com", "Email us", :subject => "NB Linkedin Enquiry", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>

app/views/services/youtube.html.erb
<div class=page-header-text>
  <div class="row">
      <h1 class="display-4 col container">Youtube</h1>
  </div>
  <div class="row">
      <h1 class="display-5 col">Why Youtube</h1>
  </div>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1> Youtube is the 2nd biggest social network in the western world with over 1.9 billion monthly active users!
         <br>
         <br>It is the channel for anyone involved in video content.
    </p1>
  </div>
</div>

</div>
<div class="page-break-text-two row">
    <h1 class="display-5 container">Register your interest</h1>
</div>

<div class="social-channel-text">
  <div class="container">
    <p1> We’re working hard at developing our growth model around Youtube and have already seen great results!
      <br>
      <br>If Youtube is something that you might be interested in when we do launch
      then register interest and be the first to hear when we do launch!
      The more people showing an interest the more sense it makes to invest
      more of our time to get it launched and out to you!
      <br>
      <br>To join the waiting list, email kieran@wearethenatureboys.com
      with the Youtube handle you'd be interested in getting help with in the future.
      <br>
      <br> or click the link below...
    </p1>
  </div>
</div>

<div class="chat-cta">
  <h2><%=mail_to "kieran@wearethenatureboys.com", "Email us", :subject => "NB Youtube Enquiry", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>

app/views/shared/_footer.html.erb
<hr>
<div class="footer container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.wearethenatureboys.com">The Nature Boys</a>
      By Max Sinclair
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_us_path %></li>
        <li><%= link_to "Instagram", instagram_path %></li>
        <li><%= link_to "Linkedin", linkedin_path %></li>
        <li><%= link_to "EC Journalists", ec_journalists_path %></li>
        <li><%= link_to "Speak to Us", speak_to_us_path %></li>
      </ul>
    </nav>
  </footer>
</div>
<hr>

app/views/shared/_logo.html.erb
<header>
<div class="logo text-center">
  <%= link_to image_tag("nblogo.png"), root_path %>
</div>
</header>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <h1 class="nav-item" id="emailus">
      <p>Get in touch:
        <br>Kieran@wearethenatureboys.com</p>
    </h1>
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Instagram", instagram_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "EC Journalists", ec_journalists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Youtube", youtube_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Linkedin", linkedin_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "About Us", about_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Speak to us", speak_to_us_path, class: 'nav-link' %>
      </li>
    </ul>
    <h1 class="nav-item" id="clientsignin">
      Client Sign In
    </h1>
  </div>

</nav>

app/views/welcome/home.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <div class="header-image">
      <h1 class="display-1"><%= image_tag("nblogo.png") %></h1>
      <h2><%=link_to 'Speak to us', speak_to_us_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
      </div>
  </div>
</div>

<div class="homepage-text">
  <div class="container">
    <h3> Social and environmentally conscious organic audience builders</h3>
  </div>
</div>
<hr>
<div class="homepage-text">
  <div class="container">
    <p1> We specialise in creating audiences within various social networks through
         highly targeted growth hacking techniques. We bring a tailored, human approach to automation.
         <br>
         <br>We're especially good with Instagram...
    </p1>
  </div>
</div>
<div class="homepage-text">
  <div class="container">
    <p1> We deliver a highly targeted, engaged audience growing at over 2,000
        new followers per month.
    </p1>
  </div>
</div>
<div class="homepage-text">
  <div class="container">
    <p1> We do this by combining our Insta empire of 200+ accounts and 2.5m
        follower base with a tailored setup on our own automation software and we
        support all of this with constant training and support!
    </p1>
  </div>
</div>
<div class="enquiry-cta">
  <h2><%=link_to 'Find out more', instagram_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>
<div class="page-break-text-three row">
    <h1 class="display-5 container">Other Hippy Magic</h1>
</div>

<div class="linkedin-and-youtube row container">
  <div class="container">
      <div class="linkedin col-sm-12 col-xs-12 col-md-4 col-lg-4 col-xl-6">
        <div class="container">
          <h2> Linkedin </h2>
          <hr>
          <p1> Linkedin is the most important B2B social network that exists today.
            <br>
            <br>We're killing it for ourselves on there and love to help others do the same!
           </p1>
        <div class="linkedin-cta">
          <h2><%=link_to 'Find out more', linkedin_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
        </div>
      </div>
    </div>
      <div class="youtube col-sm-12 col-xs-12 col-md-4 col-lg-4 col-xl-6">
          <div class="container">
            <h2> Youtube </h2>
            <hr>
            <p1> Want a future in video? Think Youtube!
              <br>
              <br>Find out what we're up to with this channel of ever increasing importance...
            </p1>
          <div class="youtube-cta">
            <h2><%=link_to 'Find out more', youtube_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="page-break-text-two row">
    <h1 class="display-5 container">Eco Companion Journalists</h1>
</div>
<div class="homepage-ec-journalist">
  <div class="container">
        <p1> <%= image_tag "EC_Journalist.png" %>
        <h2> The Eco Companion Journalist Community </h2>
        <hr>
        <p1> A lot of the creative work you might see in and around the Nature Boys world has been
          produced by a talented community of content creators named ‘Eco Companion Journalists’
          <br>
          <br>We’re proud to have partnered up with Eco Companion to support this community’s growth!
          <br>
          <br>Are you travel and nature focused and a content creator?
         </p1>
      <div class="ecj-cta">
        <h2><%=link_to 'Find out more', ec_journalists_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
      </div>
  </div>
</div>
<div class="page-break-text-four row">
    <h1 class="display-5 container">Getting to know us first</h1>
</div>
<div class="homepage-ec-journalist">
  <div class="container">
        <p1> We always love a chat so best thing to do is send us an email and we can book in a chance to speak!
         </p1>
      <div class="chat-cta">
        <h2><%=link_to 'Click to chat', speak_to_us_path, class: "btn btn-dark btn-lg btn-xlarge" %></h2>
      </div>
      <p1> Or if you’re feeling ‘enquiry-shy’ then head on over to our <%=link_to "Who Are We?", about_us_path %> page to read more.
       </p1>
  </div>
</div>

app/views/welcome/speak_to_us.html.erb
<div class=page-header-text>
  <div class="row">
      <h1 class="display-4 col container">Speak to us</h1>
  </div>
  <div class="row">
      <h1 class="display-5 col">Get our help</h1>
  </div>
</div>

<div class="social-channel-text container">
    <p1> Interested in our support with Instagram, Linkedin or Youtube?
      <br>
      <br>Just get in touch by emailing kieran@wearethenatureboys.com with who you are
       and the social account
       <br>you're interested in getting our help with. ✌🏻
       <br>
       <br> or click the link below...
    </p1>
  </div>
</div>

<div class="chat-cta">
  <h2><%=mail_to "kieran@wearethenatureboys.com", "Email us", :subject => "NB Enquiry", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>

<div class="page-break-text-four row">
    <h1 class="display-5 container">Join our team</h1>
</div>

<div class="social-channel-text container">
    <p1> We are a fun bunch and do some pretty cool stuff so I get it…
      <br>
      <br>Simply add your details to our talent pool and get an email through
      about any future openings for the Nature Boys
      <br>
      <br>AND our sister company
      Eco Companion before anyone else!
    </p1>
  </div>
</div>

<div class="talent-pool-cta">
  <h2><%=link_to 'Add your details', "https://ecocompanion.typeform.com/to/bD75nk", class: "btn btn-dark btn-lg btn-xlarge" %></h2>
</div>